# Generated by Django 5.2.4 on 2025-07-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='full_name',
        ),
    ]
