# Generated by Django 5.2 on 2025-07-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseReview',
        ),
    ]
