# Generated by Django 5.2 on 2025-07-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_assignment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='code_text',
        ),
    ]
